import enum

class ResourceType(enum.Enum):
    TEXTURE_KEY_UP = 1
    TEXTURE_KEY_RIGHT = 2
    TEXTURE_KEY_DOWN = 3
    TEXTURE_KEY_LEFT = 4
    TEXTURE_SEW_DOLL = 5
    TEXTURE_SEW_DOLL_COMPLETE = 6
    TEXTURE_STARBURST_EXPLOSION = 7
    TEXTURE_POWERWASH_GUN = 8
    TEXTURE_SIDEWALK = 9
    TEXTURE_SPLAT_1 = 10
    TEXTURE_SPLAT_2 = 11
    TEXTURE_SPLAT_STRIPE = 12
    TEXTURE_SPLAT_COFFEE = 13
    TEXTURE_SHEET_SPARKLE = 14